In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime,date
%matplotlib inline

In [22]:
df_origin = pd.read_excel(r'/home/silva/desenvolvedor/data_science/python/fundamentos/balanco.xls', sheet_name='Dem. Result.')

WARNING *** file size (69996) not 512 + multiple of sector size (512)
WARNING *** OLE2 inconsistency: SSCS size is 0 but SSAT size is non-zero

In [23]:
df_origin

,"XLSWrite 1.34 Copyright(c) 1999,2000 Axolot Data",Demonstrativo de Resultado - ITAÚSA - Trimestres Isolados,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42
0,,30/09/2018,30/06/2018,31/03/2018,31/12/2017,30/09/2017,30/06/2017,31/03/2017,31/12/2016,30/09/2016,...,30/09/2010,30/06/2010,31/03/2010,31/12/2009,30/09/2009,30/06/2009,31/03/2009,31/12/2008,30/09/2008,30/06/2008
1,Receita Bruta de Vendas e/ou Serviços,0,0,0,0,0,0,0,0,0,...,5.63217e+06,5.67984e+06,5.32205e+06,5.45022e+06,4.97114e+06,4.4849e+06,4.44562e+06,4.90156e+06,3.72186e+06,3.61761e+06
2,Deduções da Receita Bruta,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Receita Líquida de Vendas e/ou Serviços,1.511e+06,1340000,1262000,1.362e+06,1290000,1.139e+06,1178000,1.215e+06,1162000,...,5.63217e+06,5.67984e+06,5.32205e+06,5.45022e+06,4.97114e+06,4.4849e+06,4.44562e+06,4.90156e+06,3.72186e+06,3.61761e+06
4,Custo de Bens e/ou Serviços Vendidos,-1.085e+06,-999000,-947000,-948000,-945000,-860000,-921000,-938000,-884000,...,-740808,-1.04877e+06,-931824,-976078,-877896,-707707,-743658,-906208,-865526,-776644
5,Resultado Bruto,426000,341000,315000,414000,345000,279000,257000,277000,278000,...,4.89136e+06,4.63107e+06,4.39023e+06,4.47415e+06,4093248,3.7772e+06,3.70196e+06,3.99535e+06,2.85633e+06,2.84097e+06
6,Despesas Com Vendas,-194000,-175000,-165000,-180000,-184000,-165000,-157000,-163000,-157000,...,0,0,0,0,0,0,0,0,0,0
7,Despesas Gerais e Administrativas,-87000,-71000,-79000,-90000,-83000,-76000,-73000,-78000,-83000,...,-9.3891e+06,-8.8835e+06,-8.23405e+06,-8.16434e+06,-8.29762e+06,-8.51333e+06,-8.17531e+06,-1.39083e+07,-5.07945e+06,-4.42007e+06
8,Perdas pela Não Recuperabilidade de Ativos,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,Outras Receitas Operacionais,755000,338000,338000,45000,135000,108000,18000,39000,54000,...,172635,333942,362675,593712,0,620699,332226,1.45645e+06,288320,148492
10,Outras Despesas Operacionais,-297000,-230000,-571000,-182000,-103000,-49000,-233000,-328000,-39000,...,-2.41912e+06,-2.4263e+06,-2.04716e+06,-5.38687e+06,0,-2.17931e+06,-2.3486e+06,-6.57131e+06,-1.42728e+06,-1.37811e+06
11,Resultado da Equivalência Patrimonial,2328000,2058000,2.633e+06,1.844e+06,2.286e+06,2.131e+06,2.303e+06,2.123e+06,2090000,...,92619,33492,73878,55335,100410,40624,28304,-2.75832e+06,123357,-107715
12,Financeiras,-63000,-53000,-59000,-94000,-27000,-71000,-34000,-51000,-48000,...,1.19673e+07,1.08092e+07,1.01008e+07,1.37859e+07,9.0704e+06,1.2736e+07,1.06439e+07,6.63199e+06,4.80701e+06,6.49877e+06
13,Receitas Financeiras,66000,125000,56000,60000,114000,95000,106000,-298000,102000,...,2.11936e+07,1.88899e+07,1.8422e+07,1.8298e+07,1.9113e+07,1.84491e+07,2.1067e+07,2.96065e+07,1.74207e+07,5.61583e+06
14,Despesas Financeiras,-129000,-178000,-115000,-154000,-141000,-166000,-140000,247000,-150000,...,-9.22629e+06,-8.08078e+06,-8.32118e+06,-4.51207e+06,-1.00426e+07,-5.71304e+06,-1.04231e+07,-2.29745e+07,-1.26137e+07,882941
15,Resultado Não Operacional,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,58557,63486,5600
16,Receitas,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,-69086,63486,5600
17,Despesas,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,127643,0,0
18,Resultado Antes Tributação/Participações,2868000,2208000,2412000,1.757e+06,2.369e+06,2.157e+06,2.081e+06,1.819e+06,2.095e+06,...,5.3157e+06,4.49787e+06,4.64635e+06,5.3579e+06,4.96643e+06,6.48192e+06,4.18248e+06,-1.10956e+07,1.63178e+06,3587936
19,Provisão para IR e Contribuição Social,-214000,-98000,-18000,213000,-110000,-6000,-162000,128000,-82000,...,-1.93239e+06,-896174,-1.11155e+06,-1.32831e+06,-1.95353e+06,-3.22073e+06,-1.0131e+06,1.08103e+07,576434,-1.2972e+06
20,IR Diferido,67000,43000,26000,27000,144000,55000,-3000,-44000,120000,...,0,0,0,0,0,0,0,0,0,0
21,Participações/Contribuições Estatutárias,0,0,0,0,0,0,0,0,0,...,-61046,-61599,-68915,-468044,-479427,-368099,-415324,-234800,-217129,-237929
22,Reversão dos Juros sobre Capital Próprio,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
23,Part. de Acionistas Não Controladores,-239000,-106000,-20000,-55000,-53000,-16000,5000,-5000,-19000,...,-2.21144e+06,-2.35495e+06,-2.38684e+06,-2.3967e+06,-1.67743e+06,-1.88527e+06,-1852592,744973,-1071944,-1.20096e+06
24,Lucro/Prejuízo do Período,2.482e+06,2.047e+06,2400000,1.942e+06,2.35e+06,2.19e+06,1.921e+06,1.898e+06,2114000,...,1.11083e+06,1.18514e+06,1.07905e+06,1.16484e+06,856056,1007832,901471,224849,919142,851848

In [41]:
df_origin.dtypes

XLSWrite 1.34 Copyright(c) 1999,2000 Axolot Data             object
Demonstrativo de Resultado - ITAÚSA - Trimestres Isolados    object
Unnamed: 2                                                   object
Unnamed: 3                                                   object
Unnamed: 4                                                   object
Unnamed: 5                                                   object
Unnamed: 6                                                   object
Unnamed: 7                                                   object
Unnamed: 8                                                   object
Unnamed: 9                                                   object
Unnamed: 10                                                  object
Unnamed: 11                                                  object
Unnamed: 12                                                  object
Unnamed: 13                                                  object
Unnamed: 14                                                  object
Unnamed: 15                                                  object
Unnamed: 16                                                  object
Unnamed: 17                                                  object
Unnamed: 18                                                  object
Unnamed: 19                                                  object
Unnamed: 20                                                  object
Unnamed: 21                                                  object
Unnamed: 22                                                  object
Unnamed: 23                                                  object
Unnamed: 24                                                  object
Unnamed: 25                                                  object
Unnamed: 26                                                  object
Unnamed: 27                                                  object
Unnamed: 28                                                  object
Unnamed: 29                                                  object
Unnamed: 30                                                  object
Unnamed: 31                                                  object
Unnamed: 32                                                  object
Unnamed: 33                                                  object
Unnamed: 34                                                  object
Unnamed: 35                                                  object
Unnamed: 36                                                  object
Unnamed: 37                                                  object
Unnamed: 38                                                  object
Unnamed: 39                                                  object
Unnamed: 40                                                  object
Unnamed: 41                                                  object
Unnamed: 42                                                  object
dtype: object

In [42]:
df = df_origin.transpose()
df.head()

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
"XLSWrite 1.34 Copyright(c) 1999,2000 Axolot Data",,Receita Bruta de Vendas e/ou Serviços,Deduções da Receita Bruta,Receita Líquida de Vendas e/ou Serviços,Custo de Bens e/ou Serviços Vendidos,Resultado Bruto,Despesas Com Vendas,Despesas Gerais e Administrativas,Perdas pela Não Recuperabilidade de Ativos,Outras Receitas Operacionais,...,Resultado Não Operacional,Receitas,Despesas,Resultado Antes Tributação/Participações,Provisão para IR e Contribuição Social,IR Diferido,Participações/Contribuições Estatutárias,Reversão dos Juros sobre Capital Próprio,Part. de Acionistas Não Controladores,Lucro/Prejuízo do Período
Demonstrativo de Resultado - ITAÚSA - Trimestres Isolados,30/09/2018,0,0,1.511e+06,-1.085e+06,426000,-194000,-87000,0,755000,...,0,0,0,2868000,-214000,67000,0,0,-239000,2.482e+06
Unnamed: 2,30/06/2018,0,0,1340000,-999000,341000,-175000,-71000,0,338000,...,0,0,0,2208000,-98000,43000,0,0,-106000,2.047e+06
Unnamed: 3,31/03/2018,0,0,1262000,-947000,315000,-165000,-79000,0,338000,...,0,0,0,2412000,-18000,26000,0,0,-20000,2400000
Unnamed: 4,31/12/2017,0,0,1.362e+06,-948000,414000,-180000,-90000,0,45000,...,0,0,0,1.757e+06,213000,27000,0,0,-55000,1.942e+06

In [43]:
df = df.reset_index()

In [45]:
df.index

RangeIndex(start=0, stop=43, step=1)

In [26]:
formatter_string = "%dd/%mm/%Y"

In [14]:
datetime.strptime('30/09/2018',formatter_string)

ValueError: time data '30/09/2018' does not match format '%dd/%mm/%Y'

In [80]:
df = df.set_index(df[df.columns[0]])

In [84]:
df = df.ix[:,]

/home/silva/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

In [86]:
 df.pivot(index='date', columns='variable', values='value')

KeyError: 'date'

In [59]:
x = df.iloc[23]

TypeError: Index(...) must be called with a collection of some kind, 0 was passed